- name: install dependencies
  apt:
    name: "{{item}}"
    state: "{{ state }}"
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: add GPG key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_facts['distribution']|lower }}/gpg"
    validate_certs: false
  when: 
    - state != 'absent'

- name: Add docker repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_facts['distribution']|lower }} {{ ansible_facts['distribution_release']|lower }} stable"
    state: "{{ state }}"
    

- name: install/delete docker required packages
  apt:
    name: "{{item}}"
    state: "{{ state }}"
    update_cache: yes
  loop: "{{ packages_list }}"