services:
  nginx:
    image: "nginx:{{ nginx_tag }}"
    deploy:
      mode: global
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl/

  iconserver:
    image: "matthiasluedtke/iconserver:{{ besticon_tag }}"
    restart: always
    deploy:
      mode: replicated
      replicas: {{ replicas }}
    environment:
      ADDRESS: ${ADDRESS}
      CACHE_SIZE_MB: ${CACHE_SIZE_MB}
      CORS_ENABLED: ${CORS_ENABLED}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS}	
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}	
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}	
      CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS}
      CORS_DEBUG: ${CORS_DEBUG}
      DISABLE_BROWSE_PAGES: ${DISABLE_BROWSE_PAGES}
      HOST_ONLY_DOMAINS: ${HOST_ONLY_DOMAINS}
      HTTP_CLIENT_TIMEOUT: ${HTTP_CLIENT_TIMEOUT}
      HTTP_MAX_AGE_DURATION: ${HTTP_MAX_AGE_DURATION}
      HTTP_USER_AGENT: ${HTTP_USER_AGENT}
      METRICS_PATH: ${METRICS_PATH}
      POPULAR_SITES: ${POPULAR_SITES}
      PORT: ${PORT}
      SERVER_MODE: ${SERVER_MODE}

